apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: media-manager
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["create"]
- apiGroups: [""]
  resourceNames: ["media-manager"]
  resources: ["secrets"]
  verbs: ["get", "update", "patch"]
