apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: media-manager
  namespace: {{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: media-manager
roleRef:
  kind: Role
  name: media-manager
  apiGroup: rbac.authorization.k8s.io
