apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: openvpn
  namespace: {{ .Release.Namespace }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: global-secrets
  data:
    - secretKey: OPENVPN_PASSWORD
      remoteRef:
        key: external
        property: openvpn-password
    - secretKey: OPENVPN_USERNAME
      remoteRef:
        key: external
        property: openvpn-username
