app-template:
  serviceAccount:
    name: homepage
    create: true
    enableRbac: true
  controllers:
    main:
      containers:
        main:
          image:
            repository: ghcr.io/gethomepage/homepage
            tag: v1.9.0
          env:
            HOMEPAGE_ALLOWED_HOSTS: "*"
          envFrom:
            - secret: homepage-secret
  service:
    main:
      ports:
        http:
          port: 3000
          protocol: HTTP
  ingress:
    main:
      enabled: true
      className: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hosts:
        - host: &host home.malford.io
          paths:
            - path: /
              pathType: Prefix
              service:
                name: main
                port: http
      tls:
        - hosts:
            - *host
          secretName: homepage-tls-certificate
  persistence:
    config:
      enabled: true
      type: configMap
      name: homepage-config
      globalMounts:
        - path: /app/config/settings.yaml
          subPath: settings.yaml
        - path: /app/config/widgets.yaml
          subPath: widgets.yaml
        - path: /app/config/services.yaml
          subPath: services.yaml
        - path: /app/config/bookmarks.yaml
          subPath: bookmarks.yaml
        - path: /app/config/kubernetes.yaml
          subPath: kubernetes.yaml
  configMaps:
    config:
      enabled: true
      data:
        settings.yaml: |
          cardBlur: md
          theme: dark
          headerStyle: boxed
          hideVersion: false
        widgets.yaml: |
          - kubernetes:
              cluster:
                show: true
                cpu: true
                memory: true
                showLabel: true
                label: "cluster"
              nodes:
                show: true
                cpu: true
                memory: true
                showLabel: true
          - ceph:
              url: http://rook-ceph-mgr-dashboard.rook-ceph.svc.cluster.local:8443
          - openmeteo:
              label: Brooklyn
              latitude: 40.6782
              longitude: -73.9442
              units: imperial
              cache: 5
          - search:
              provider: duckduckgo
              target: _blank
        kubernetes.yaml: |
          mode: cluster
        services.yaml: |
          - Popular:
            - Jellyfin:
                href: https://jellyfin.malford.io
                description: Media system (movies, music, etc.)
                icon: jellyfin.svg
                widget:
                  type: jellyfin
                  url: http://jellyfin.media.svc.cluster.local:8096
                  key: '{{ `{{HOMEPAGE_VAR_JELLYFIN_API_KEY}}` }}'
                  enableBlocks: true
                  enableNowPlaying: true
            - Plex:
                href: https://plex.malford.io
                description: Alternate media system
                icon: plex.svg
                widget:
                  type: plex
                  url: http://plex.media.svc.cluster.local:32400
                  key: '{{ `{{HOMEPAGE_VAR_PLEX_TOKEN}}` }}'
            - Paperless:
                href: https://paperless.malford.io
                description: Document management system
                icon: paperless.svg
                widget:
                  type: paperlessngx
                  url: http://paperless.paperless.svc.cluster.local:8000
                  key: '{{ `{{HOMEPAGE_VAR_PAPERLESS_API_KEY}}` }}'
          - Management:
            - Transmission:
                href: https://transmission.malford.io
                description: Bittorrent client
                icon: transmission.svg
                widget:
                  type: transmission
                  url: http://transmission.media.svc.cluster.local:9091
            - SABnzbd:
                href: https://sabnzbd.malford.io
                description: Usenet download client
                icon: sabnzbd.svg
                widget:
                  type: sabnzbd
                  url: http://sabnzbd.media.svc.cluster.local:8080
                  key: '{{ `{{HOMEPAGE_VAR_SABNZBD_API_KEY}}` }}'
            - Prowlarr:
                href: https://prowlarr.malford.io
                description: Indexer manager
                icon: prowlarr.svg
                widget:
                  type: prowlarr
                  url: http://prowlarr.media.svc.cluster.local:9696
                  key: '{{ `{{HOMEPAGE_VAR_PROWLARR_API_KEY}}` }}'
            - Radarr:
                href: https://radarr.malford.io
                description: Movie manager
                icon: radarr.svg
                widget:
                  type: radarr
                  url: http://radarr.media.svc.cluster.local:7878
                  key: '{{ `{{HOMEPAGE_VAR_RADARR_API_KEY}}` }}'
            - Sonarr:
                href: https://sonarr.malford.io
                description: TV show manager
                icon: sonarr.svg
                widget:
                  type: sonarr
                  url: http://sonarr.media.svc.cluster.local:8989
                  key: '{{ `{{HOMEPAGE_VAR_SONARR_API_KEY}}` }}'
            - Lidarr:
                href: https://lidarr.malford.io
                description: Music manager
                icon: lidarr.svg
                widget:
                  type: lidarr
                  url: http://lidarr.media.svc.cluster.local:8686
                  key: '{{ `{{HOMEPAGE_VAR_LIDARR_API_KEY}}` }}'
            - Jackett:
                href: https://jackett.malford.io
                description: Indexer proxy
                icon: jackett.svg
            - Kanidm:
                href: https://auth.malford.io
                description: Identity management
                icon: https://auth.malford.io/pkg/img/logo-square.svg
          - Development:
            - Gitea:
                href: https://git.malford.io
                description: Git forge
                icon: gitea.svg
                ping: http://gitea-http.gitea
            - Woodpecker:
                href: https://ci.malford.io
                description: Continuous integration
                icon: woodpecker-ci.svg
            - ArgoCD:
                href: https://argocd.malford.io
                description: Continuous deployment
                icon: argo-cd.svg
            - Registry:
                href: https://registry.malford.io
                description: Container registry
                icon: docker.svg
            - Grafana:
                href: https://grafana.malford.io
                description: Observability dashboards
                icon: grafana.svg
                widget:
                  type: grafana
                  url: http://grafana.grafana.svc.cluster.local:3000
                  username: admin
                  password: '{{ `{{HOMEPAGE_VAR_GRAFANA_PASSWORD}}` }}'
          - Utilities:
            - Chatbot:
                href: https://ai.malford.io
                description: Ollama agentic chatbot
                icon: ollama-dark.svg
            - Excalidraw:
                href: https://draw.malford.io
                description: Virtual whiteboard
                icon: excalidraw.svg
            - Speedtest:
                href: https://speedtest.malford.io
                description: Internal network speed test
                icon: openspeedtest.png
        bookmarks.yaml: |
          - Homelab:
            - Public homelab repository:
              - href: https://github.com/malford/homelab
                icon: github.svg
          - Managed services:
            - Cloudflare:
              - href: https://dash.cloudflare.com
                icon: cloudflare.svg
            - Terraform Cloud:
              - href: https://app.terraform.io
                icon: terraform.svg
          - Infrastructure:
            - Router:
              - href: https://unifi.local.mmalford.com/
                icon: ubiquiti.svg
            - Google Cloud:
              - href: https://console.cloud.google.com
                icon: google-cloud-platform.svg
