app-template:
  controllers:
    excalidraw:
      containers:
        app:
          image:
            repository: docker.io/excalidraw/excalidraw
            tag: latest
  service:
    app:
      controller: excalidraw
      ports:
        http:
          port: 80
  ingress:
    app:
      className: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        external-dns.alpha.kubernetes.io/target: homelab-tunnel.malford.io
        external-dns.alpha.kubernetes.io/cloudflare-proxied: 'true'
      hosts:
        - host: &host draw.malford.io
          paths:
            - path: /
              pathType: Prefix
              service:
                identifier: app
                port: http
      tls:
        - hosts:
            - *host
          secretName: excalidraw-tls-certificate
