# In apps/jellyfin/templates/config-volume.yaml

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-config-pv
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.3.20
    path: /volume1/clusterStorage/config
    readOnly: false
  mountOptions:
    - hard
    - nfsvers=4.1

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  # This name must match what you use in values.yaml
  name: jellyfin-config
  namespace: {{ .Release.Namespace }} # This ensures it's created in the 'jellyfin' namespace
spec:
  # Use an empty storageClassName to match the PV
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi # Must be <= the PV capacity
  # This explicitly binds this PVC to our manually created PV
  volumeName: jellyfin-config-pv
