---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-media-pv
spec:
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-csi
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - hard
    - nfsvers=4.1
    - rsize=1048576
    - wsize=1048576
    - async
    - noatime
    - nodiratime
  csi:
    driver: nfs.csi.k8s.io
    volumeHandle: jellyfin-media-pv
    volumeAttributes:
      server: 192.168.3.20
      share: /volume1/media

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-media
  namespace: {{ .Release.Namespace }}
spec:
  storageClassName: nfs-csi
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Ti
  volumeName: jellyfin-media-pv
