apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jellyfin
  namespace: {{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: jellyfin
roleRef:
  kind: Role
  name: jellyfin
  apiGroup: rbac.authorization.k8s.io
