all:
  vars:
    control_plane_endpoint: 192.168.3.200
    load_balancer_ip_pool:
      - 192.168.3.224/27
metal:
  children:
    masters:
      hosts:
        metal0: {ansible_host: 192.168.3.201, mac: '6c:4b:90:57:ee:ee', disk: sda, network_interface: eno1}
