apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}-secret
  namespace: {{ .Release.Namespace }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: global-secrets
  data:
    - secretKey: OPENCLAW_GATEWAY_TOKEN
      remoteRef:
        key: external
        property: openclaw-gateway-token
    - secretKey: ANTHROPIC_API_KEY
      remoteRef:
        key: external
        property: anthropic-api-key
    - secretKey: OPENAI_API_KEY
      remoteRef:
        key: external
        property: openai-api-key
    - secretKey: TELEGRAM_BOT_TOKEN
      remoteRef:
        key: external
        property: telegram-bot-token
    - secretKey: TELEGRAM_USER_ID
      remoteRef:
        key: external
        property: telegram-user-id
    - secretKey: GITHUB_TOKEN
      remoteRef:
        key: external
        property: github-pat-openclaw
