apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}-secret
  namespace: {{ .Release.Namespace }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: global-secrets
  data:
    - secretKey: HOMEPAGE_VAR_JELLYFIN_API_KEY
      remoteRef:
        key: external
        property: jellyfin-api-key
    - secretKey: HOMEPAGE_VAR_PLEX_TOKEN
      remoteRef:
        key: external
        property: plex-token
    - secretKey: HOMEPAGE_VAR_PAPERLESS_API_KEY
      remoteRef:
        key: external
        property: paperless-api-key
    - secretKey: HOMEPAGE_VAR_SABNZBD_API_KEY
      remoteRef:
        key: external
        property: sabnzbd-api-key
    - secretKey: HOMEPAGE_VAR_PROWLARR_API_KEY
      remoteRef:
        key: external
        property: prowlarr-api-key
    - secretKey: HOMEPAGE_VAR_RADARR_API_KEY
      remoteRef:
        key: external
        property: radarr-api-key
    - secretKey: HOMEPAGE_VAR_SONARR_API_KEY
      remoteRef:
        key: external
        property: sonarr-api-key
    - secretKey: HOMEPAGE_VAR_LIDARR_API_KEY
      remoteRef:
        key: external
        property: lidarr-api-key
    - secretKey: HOMEPAGE_VAR_GRAFANA_PASSWORD
      remoteRef:
        key: external
        property: grafana-admin-password
