apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}-secret
  namespace: {{ .Release.Namespace }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: global-secrets
  data:
    - secretKey: UP_UNIFI_DEFAULT_USER
      remoteRef:
        key: external
        property: unifi-admin-username
    - secretKey: UP_UNIFI_DEFAULT_PASS
      remoteRef:
        key: external
        property: unifi-admin-password
