apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: media-stack
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: {{ .Values.argocd-apps.applicationsets.root.generators[0].git.repoURL | quote }}
    targetRevision: {{ .Values.argocd-apps.applicationsets.root.generators[0].git.revision | quote }}
    path: apps
    directory:
      include: "media-stack.yaml"
      recurse: false
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  syncPolicy:
    automated: { prune: true, selfHeal: true }
