---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: eufy-events-pv
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-csi
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - soft
    - timeo=50
    - retrans=3
    - nfsvers=3
    - rsize=131072
    - wsize=131072
    - noatime
    - nodiratime
    - tcp
    - async
    - nolock
  csi:
    driver: nfs.csi.k8s.io
    volumeHandle: eufy-events-pv
    volumeAttributes:
      server: 192.168.3.20
      share: /volume1/eufy-events
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: eufy-events
  namespace: {{ .Release.Namespace }}
spec:
  storageClassName: nfs-csi
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  volumeName: eufy-events-pv
