apiVersion: v1
kind: Namespace
metadata:
  name: media
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lidarr # The name of this specific app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://git.malford.io/ops/homelab'
    path: apps/lidarr # Path to this app's values
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: media # All apps go to the same namespace
  syncPolicy:
    automated: { prune: true, selfHeal: true }
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: radarr # The name of this specific app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://git.malford.io/ops/homelab'
    path: apps/radarr # Path to this app's values
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: media # All apps go to the same namespace
  syncPolicy:
    automated: { prune: true, selfHeal: true }
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sonarr # The name of this specific app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://git.malford.io/ops/homelab'
    path: apps/sonarr # Path to this app's values
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: media # All apps go to the same namespace
  syncPolicy:
    automated: { prune: true, selfHeal: true }
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prowlarr # The name of this specific app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://git.malford.io/ops/homelab'
    path: apps/prowlarr # Path to this app's values
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: media # All apps go to the same namespace
  syncPolicy:
    automated: { prune: true, selfHeal: true }
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jackett # The name of this specific app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://git.malford.io/ops/homelab'
    path: apps/jackett # Path to this app's values
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: media # All apps go to the same namespace
  syncPolicy:
    automated: { prune: true, selfHeal: true }
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sabnzbd # The name of this specific app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://git.malford.io/ops/homelab'
    path: apps/sabnzbd # Path to this app's values
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: media # All apps go to the same namespace
  syncPolicy:
    automated: { prune: true, selfHeal: true }
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jellyseerr # The name of this specific app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://git.malford.io/ops/homelab'
    path: apps/jellyseerr # Path to this app's values
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: media # All apps go to the same namespace
  syncPolicy:
    automated: { prune: true, selfHeal: true }
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: plex # The name of this specific app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://git.malford.io/ops/homelab'
    path: apps/plex # Path to this app's values
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: media # All apps go to the same namespace
  syncPolicy:
    automated: { prune: true, selfHeal: true }
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flaresolverr # The name of this specific app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://git.malford.io/ops/homelab'
    path: apps/flaresolverr # Path to this app's values
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: media # All apps go to the same namespace
  syncPolicy:
    automated: { prune: true, selfHeal: true }
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: transmission # The name of this specific app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://git.malford.io/ops/homelab'
    path: apps/transmission # Path to this app's values
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: media # All apps go to the same namespace
  syncPolicy:
    automated: { prune: true, selfHeal: true }
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jellyfin # The name of this specific app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://git.malford.io/ops/homelab'
    path: apps/jellyfin # Path to this app's values
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: media # All apps go to the same namespace
  syncPolicy:
    automated: { prune: true, selfHeal: true }
